lobby-server: lobby
feedback-message: "&7You have been teleported to Hub..."
messages:
  console-only: "&cThis command can be executed only for console!"
  config-reloaded: "&aConfiguration reloaded successfully!"
